"""update profile model

Revision ID: c88697c1e8e8
Revises: 2135ee207374
Create Date: 2024-12-09 21:42:17.908506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88697c1e8e8'
down_revision: Union[str, None] = '2135ee207374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'cover_src',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'avatar_src',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'avatar_src',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'cover_src',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profiles', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
